# Generated by Django 5.2.3 on 2025-07-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupado'), ('reserved', 'Reservado'), ('maintenance', 'Mantenimiento')], default='available', max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('', 'Sin tipo'), ('eléctrico', 'Eléctrico'), ('discapacitado', 'Discapacitado'), ('motocicleta', 'Motocicleta')], default='', max_length=20)),
                ('tarifa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='espacios',
        ),
    ]
