# Generated by Django 5.2.3 on 2025-07-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_espacio_delete_espacios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='estado',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
