# Generated by Django 5.2.3 on 2025-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='correo',
        ),
        migrations.AddField(
            model_name='registro',
            name='confirmar_contraseña',
            field=models.TextField(default=1, verbose_name='confirmar_contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='correo_electronico',
            field=models.TextField(default=1, verbose_name='correo_electronico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='nombre_completo',
            field=models.TextField(default=1, verbose_name='nombre_completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='placa_vehiculo',
            field=models.TextField(default=1, verbose_name='placa_vehiculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='telefono',
            field=models.IntegerField(default=1, verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
