# Generated by Django 5.2.3 on 2025-06-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_remove_entrada_h_d_m_entrada_dia_entrada_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='hora',
            field=models.TimeField(verbose_name='hora'),
        ),
    ]
