# Generated by Django 5.2.3 on 2025-06-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.TextField(verbose_name='correo')),
                ('contraseña', models.TextField(verbose_name='contraseña')),
            ],
        ),
    ]
