# Generated by Django 5.2.3 on 2025-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_registro_correo_registro_confirmar_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='placa_vehiculo',
        ),
        migrations.AddField(
            model_name='registro',
            name='placa_de_vehiculo',
            field=models.IntegerField(default=1, verbose_name='placa_de_vehiculo'),
            preserve_default=False,
        ),
    ]
