# Generated by Django 5.2.3 on 2025-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_remove_registro_placa_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='placa_de_vehiculo',
            field=models.TextField(verbose_name='placa_de_vehiculo'),
        ),
    ]
