# Generated by Django 5.2.3 on 2025-07-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_alter_espacio_estado_alter_espacio_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='placa_vehiculo',
            field=models.TextField(default=1, verbose_name='placa_vehiculo'),
            preserve_default=False,
        ),
    ]
